/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladores.Coordinador;
import static Vista.InicioVista.escritorio;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Genesis Vargas
 */
public class AgregarClienteVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public static Coordinador coordinador;
    
    public AgregarClienteVista() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true); 
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
           (desktopSize.height- jInternalFrameSize.height)/2);
    }
    
    public AgregarClienteVista(Coordinador coordinador) {
        initComponents();
        this.setResizable(false);
        this.setVisible(true); 
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
           (desktopSize.height- jInternalFrameSize.height)/2);
        this.coordinador = coordinador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_fecha_nac = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        lbl_tel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Registrar cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmd_agregar.setBackground(new java.awt.Color(0, 51, 204));
        cmd_agregar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        cmd_agregar.setForeground(new java.awt.Color(255, 255, 255));
        cmd_agregar.setText("Agregar");
        cmd_agregar.setBorder(null);
        cmd_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmd_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmd_agregarMouseExited(evt);
            }
        });
        cmd_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 99, 36));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_id.setText("Identificación:");
        jPanel2.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        lbl_nombre.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");
        jPanel2.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 23));

        lbl_fecha.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_fecha.setText("Fecha de nacimiento:");
        jPanel2.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 23));

        lbl_correo.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_correo.setText("Correo:");
        jPanel2.add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 81, 22));

        txt_correo.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 20));

        txt_fecha_nac.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_fecha_nac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha_nac.setText("YYYY-MM-DD");
        jPanel2.add(txt_fecha_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, 20));

        txt_nombre.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 20));

        txt_id.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 20));

        txt_tel.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 20));

        lbl_tel.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_tel.setText("Teléfono:");
        jPanel2.add(lbl_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 81, 22));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 310, 160));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel4.setText("Datos del cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 540, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_agregarMouseEntered
        cmd_agregar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_cmd_agregarMouseEntered

    private void cmd_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_agregarMouseExited
        cmd_agregar.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_cmd_agregarMouseExited

    private void cmd_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarActionPerformed

        if ("".equals(this.txt_id.getText())) {
            JOptionPane.showMessageDialog(null, "ERROR: Es necesario que ingrese el número de identificación",
                "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Operación realizada correctamente", "Registrar cliente", JOptionPane.INFORMATION_MESSAGE);
            ClienteVista ver_ventana = new ClienteVista();
            InicioVista.escritorio.add(ver_ventana);
            this.setVisible(false);
            ver_ventana.show();
        }
    }//GEN-LAST:event_cmd_agregarActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed
    
    public void limpiar(){
        this.getTxt_id().setText("");
        this.getTxt_nombre().setText("");
        this.getTxt_fecha_nac().setText("");
        this.getTxt_telefono().setText("");
        this.getTxt_correo().setText("");
    }
    
    public JTextField getTxt_correo() {
        return txt_correo;
    }

    public void setTxt_correo(JTextField txt_correo1) {
        this.txt_correo = txt_correo1;
    }

    public JTextField getTxt_fecha_nac() {
        return txt_fecha_nac;
    }

    public void setTxt_fecha_nac(JTextField txt_fecha_nac) {
        this.txt_fecha_nac = txt_fecha_nac;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

    public JTextField getTxt_telefono() {
        return txt_tel;
    }

    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_tel = txt_telefono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_fecha_nac;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
