/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Genes
 */
public class FacturaVentaVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form FacturaVenta
     */
    public FacturaVentaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_id_fac = new javax.swing.JLabel();
        txt_id_fac_c = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_compra = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_id_prod = new javax.swing.JLabel();
        txt_id_fac_prod = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Tabla Factura venta");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icon_fac_vent.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id_fac.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_id_fac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id_fac.setText("Cod. Factura");
        getContentPane().add(lbl_id_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        txt_id_fac_c.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_id_fac_c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_fac_c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        getContentPane().add(txt_id_fac_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 120, -1));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de factura venta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_arriba.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 220, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_largo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 30));

        tabla_compra.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        tabla_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "Pablo Emilio", "2020-06-12", "666000"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod. Factura", "Identificación", "Nombre del cliente", "Fecha ", "MONTO TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla_compra.setGridColor(new java.awt.Color(0, 51, 204));
        tabla_compra.setName(""); // NOI18N
        tabla_compra.setRequestFocusEnabled(false);
        tabla_compra.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tabla_compra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_compra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 704, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_arriba.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_largo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 390, 800, 40));

        lbl_id_prod.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_id_prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id_prod.setText("Cod. Producto");
        getContentPane().add(lbl_id_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        txt_id_fac_prod.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_id_fac_prod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_fac_prod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        getContentPane().add(txt_id_fac_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id_fac;
    private javax.swing.JLabel lbl_id_prod;
    private javax.swing.JTable tabla_compra;
    private javax.swing.JTextField txt_id_fac_c;
    private javax.swing.JTextField txt_id_fac_prod;
    // End of variables declaration//GEN-END:variables
}
