/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Genesis Vargas
 */
public class Inicio extends javax.swing.JFrame {
    
    public Login usuario;
  
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        
        initComponents();

        this.setSize(810,564);
        this.setResizable(false);
        this.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_prod = new javax.swing.JMenu();
        jmi_mostrar_prod = new javax.swing.JMenuItem();
        jmi_agg_prod = new javax.swing.JMenuItem();
        jmi_buscar_prod = new javax.swing.JMenuItem();
        jmi_eliminar_prod = new javax.swing.JMenuItem();
        jm_prov = new javax.swing.JMenu();
        jmi_agg_prov = new javax.swing.JMenuItem();
        jmi_buscar_prov = new javax.swing.JMenuItem();
        jmi_eliminar_prov = new javax.swing.JMenuItem();
        jmi_mostrar_prov = new javax.swing.JMenuItem();
        jm_cliente = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_agg_cliente = new javax.swing.JMenuItem();
        jmi_buscar_cliente = new javax.swing.JMenuItem();
        jm_compra = new javax.swing.JMenu();
        jm_venta = new javax.swing.JMenu();
        jm_factura_c = new javax.swing.JMenu();
        jm_factura_v = new javax.swing.JMenu();
        jm_dev = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        escritorio.setPreferredSize(new java.awt.Dimension(810, 543));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N

        jm_prod.setText("Producto");
        jm_prod.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N

        jmi_mostrar_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jmi_mostrar_prod.setText("Ver productos");
        jmi_mostrar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mostrar_prodActionPerformed(evt);
            }
        });
        jm_prod.add(jmi_mostrar_prod);

        jmi_agg_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jmi_agg_prod.setText("Agregar ");
        jmi_agg_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agg_prodActionPerformed(evt);
            }
        });
        jm_prod.add(jmi_agg_prod);

        jmi_buscar_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jmi_buscar_prod.setText("Buscar ");
        jmi_buscar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_buscar_prodActionPerformed(evt);
            }
        });
        jm_prod.add(jmi_buscar_prod);

        jmi_eliminar_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jmi_eliminar_prod.setText("Eliminar");
        jmi_eliminar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminar_prodActionPerformed(evt);
            }
        });
        jm_prod.add(jmi_eliminar_prod);

        jMenuBar1.add(jm_prod);

        jm_prov.setText("Proveedor");
        jm_prov.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N

        jmi_agg_prov.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jmi_agg_prov.setText("Agregar");
        jmi_agg_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agg_provActionPerformed(evt);
            }
        });
        jm_prov.add(jmi_agg_prov);

        jmi_buscar_prov.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jmi_buscar_prov.setText("Buscar");
        jmi_buscar_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_buscar_provActionPerformed(evt);
            }
        });
        jm_prov.add(jmi_buscar_prov);

        jmi_eliminar_prov.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jmi_eliminar_prov.setText("Eliminar");
        jmi_eliminar_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminar_provActionPerformed(evt);
            }
        });
        jm_prov.add(jmi_eliminar_prov);

        jmi_mostrar_prov.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jmi_mostrar_prov.setText("Mostrar");
        jmi_mostrar_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mostrar_provActionPerformed(evt);
            }
        });
        jm_prov.add(jmi_mostrar_prov);

        jMenuBar1.add(jm_prov);

        jm_cliente.setText("Cliente");
        jm_cliente.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jm_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_clienteActionPerformed(evt);
            }
        });
        jm_cliente.add(jSeparator1);

        jmi_agg_cliente.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jmi_agg_cliente.setText("Agregar");
        jmi_agg_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agg_clienteActionPerformed(evt);
            }
        });
        jm_cliente.add(jmi_agg_cliente);

        jmi_buscar_cliente.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jmi_buscar_cliente.setText("Buscar");
        jmi_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_buscar_clienteActionPerformed(evt);
            }
        });
        jm_cliente.add(jmi_buscar_cliente);

        jm_compra.setFocusable(false);
        jm_compra.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jm_cliente.add(jm_compra);

        jMenuBar1.add(jm_cliente);

        jm_venta.setText("Venta");
        jm_venta.setFocusable(false);
        jm_venta.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jMenuBar1.add(jm_venta);

        jm_factura_c.setText("Factura Compra");
        jm_factura_c.setFocusable(false);
        jm_factura_c.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenuBar1.add(jm_factura_c);

        jm_factura_v.setText("Factura Venta");
        jm_factura_v.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jMenuBar1.add(jm_factura_v);

        jm_dev.setText("Devolución");
        jm_dev.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenuBar1.add(jm_dev);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_clienteActionPerformed

    private void jmi_agg_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agg_prodActionPerformed
        // TODO add your handling code here:
        AgregarProducto ver_ventana = new AgregarProducto();
        escritorio.add(ver_ventana);
        ver_ventana.show();
        
    }//GEN-LAST:event_jmi_agg_prodActionPerformed

    private void jmi_buscar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_buscar_prodActionPerformed
       
        String nombre;
        nombre = JOptionPane.showInputDialog("Digita el nombre del producto:  ");     
        Producto ver_ventana = new Producto();
        escritorio.add(ver_ventana);
        ver_ventana.show();
        
    }//GEN-LAST:event_jmi_buscar_prodActionPerformed

    private void jmi_eliminar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminar_prodActionPerformed
        String nombre;
        nombre = JOptionPane.showInputDialog("Digita el nombre del producto:  ");     
        Producto ver_ventana = new Producto();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_eliminar_prodActionPerformed

    private void jmi_mostrar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mostrar_prodActionPerformed
        Producto ver_ventana = new Producto();
        escritorio.add(ver_ventana);
        ver_ventana.show();        
    }//GEN-LAST:event_jmi_mostrar_prodActionPerformed

    private void jmi_agg_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agg_provActionPerformed
        // TODO add your handling code here:
        AgregarProveedor ver_ventana = new AgregarProveedor();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_agg_provActionPerformed

    private void jmi_mostrar_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mostrar_provActionPerformed
        // TODO add your handling code here:
        Proveedor ver_ventana = new Proveedor();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_mostrar_provActionPerformed

    private void jmi_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_buscar_clienteActionPerformed
        String id;
        id = JOptionPane.showInputDialog("Digita número de documento:  "); 
        AgregarCliente ver_ventana = new AgregarCliente();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_buscar_clienteActionPerformed

    private void jmi_eliminar_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminar_provActionPerformed
        String nombre;
        nombre = JOptionPane.showInputDialog("Digita el número de NIT:  "); 
        Proveedor ver_ventana = new Proveedor();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_eliminar_provActionPerformed

    private void jmi_buscar_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_buscar_provActionPerformed
        String nombre;
        nombre = JOptionPane.showInputDialog("Digita el número de NIT:  "); 
        Proveedor ver_ventana = new Proveedor();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_buscar_provActionPerformed

    private void jmi_agg_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agg_clienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente ver_ventana = new AgregarCliente();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_jmi_agg_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jm_cliente;
    private javax.swing.JMenu jm_compra;
    private javax.swing.JMenu jm_dev;
    private javax.swing.JMenu jm_factura_c;
    private javax.swing.JMenu jm_factura_v;
    private javax.swing.JMenu jm_prod;
    private javax.swing.JMenu jm_prov;
    private javax.swing.JMenu jm_venta;
    private javax.swing.JMenuItem jmi_agg_cliente;
    private javax.swing.JMenuItem jmi_agg_prod;
    private javax.swing.JMenuItem jmi_agg_prov;
    private javax.swing.JMenuItem jmi_buscar_cliente;
    private javax.swing.JMenuItem jmi_buscar_prod;
    private javax.swing.JMenuItem jmi_buscar_prov;
    private javax.swing.JMenuItem jmi_eliminar_prod;
    private javax.swing.JMenuItem jmi_eliminar_prov;
    private javax.swing.JMenuItem jmi_mostrar_prod;
    private javax.swing.JMenuItem jmi_mostrar_prov;
    // End of variables declaration//GEN-END:variables
}
