/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladores.Coordinador;
import static Vista.InicioVista.escritorio;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Genesis Vargas
 */
public class ModificarCompraVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarCompra
     */
    public static Coordinador coordinador;
    
    public ModificarCompraVista() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true); 
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
           (desktopSize.height- jInternalFrameSize.height)/2);    
    }
    
    public ModificarCompraVista(Coordinador coordinador) {
        this.coordinador = coordinador;
        initComponents();
        this.setResizable(false);
        this.setVisible(true); 
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
           (desktopSize.height- jInternalFrameSize.height)/2);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cmd_modificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_prov = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        lbl_fecha = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        lbl_dto1 = new javax.swing.JLabel();
        txt_dto = new javax.swing.JTextField();
        lbl_cant = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        lbl_precio_c = new javax.swing.JLabel();
        txt_precio_c = new javax.swing.JTextField();
        lbl_prod = new javax.swing.JLabel();
        txt_nombre_prod = new javax.swing.JTextField();
        lbl_lote = new javax.swing.JLabel();
        txt_lote = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Modificar compra");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icon_buscar.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmd_modificar.setBackground(new java.awt.Color(0, 51, 204));
        cmd_modificar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        cmd_modificar.setForeground(new java.awt.Color(255, 255, 255));
        cmd_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icon_buscar.png"))); // NOI18N
        cmd_modificar.setText("Modificar");
        cmd_modificar.setBorder(null);
        cmd_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmd_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmd_modificarMouseExited(evt);
            }
        });
        cmd_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 100, 32));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 130, 40));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 160, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 410, 680, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/fondo_derecha.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -30, 210, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_prov.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbl_prov.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_prov.setText("NIT proveedor:");
        jPanel1.add(lbl_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 22));

        txt_nit.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_nit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, -1));

        lbl_fecha.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_fecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_fecha.setText("Fecha:");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 73, 22));

        txt_fecha.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setText("yyyy-mm-dd");
        txt_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fechaMouseClicked(evt);
            }
        });
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 149, -1));

        lbl_dto1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_dto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_dto1.setText("Descuento:");
        jPanel1.add(lbl_dto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 73, 22));

        txt_dto.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_dto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dtoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        lbl_cant.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_cant.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_cant.setText("Cantidad:");
        jPanel1.add(lbl_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 73, 22));

        txt_cant.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_cant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        lbl_precio_c.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        lbl_precio_c.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_precio_c.setText("Precio compra:");
        jPanel1.add(lbl_precio_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, -1));

        txt_precio_c.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_precio_c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precio_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precio_cActionPerformed(evt);
            }
        });
        jPanel1.add(txt_precio_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, -1));

        lbl_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbl_prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_prod.setText("Cod. Producto:");
        jPanel1.add(lbl_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 22));

        txt_nombre_prod.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_nombre_prod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_prodActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        lbl_lote.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbl_lote.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_lote.setText("Lote:");
        jPanel1.add(lbl_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, 22));

        txt_lote.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txt_lote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loteActionPerformed(evt);
            }
        });
        jPanel1.add(txt_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 360, 310));

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de compra:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_precio_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precio_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precio_cActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void cmd_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_modificarActionPerformed
//        coordinador.modificarCompra();
    }//GEN-LAST:event_cmd_modificarActionPerformed

    private void txt_loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loteActionPerformed

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_nombre_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_prodActionPerformed

    private void txt_dtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dtoActionPerformed

    private void txt_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantActionPerformed

    private void cmd_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_modificarMouseEntered
        // TODO add your handling code here:
        cmd_modificar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_cmd_modificarMouseEntered

    private void cmd_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_modificarMouseExited
        // TODO add your handling code here:
        cmd_modificar.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_cmd_modificarMouseExited

    private void txt_fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fechaMouseClicked
       this.getTxt_fecha().setText("");
    }//GEN-LAST:event_txt_fechaMouseClicked
    
    public void limpiar(){
        this.getTxt_cant().setText("");
        this.getTxt_dto().setText("");
        this.getTxt_fecha().setText("");
        this.getTxt_lote().setText("");
        this.getTxt_nit().setText("");
        this.getTxt_nombre_prod().setText("");
        this.getTxt_precio_c().setText("");        
    }
    
    public JTextField getTxt_cant() {
        return txt_cant;
    }

    public void setTxt_cant(JTextField txt_cant) {
        this.txt_cant = txt_cant;
    }

    public JTextField getTxt_dto() {
        return txt_dto;
    }

    public void setTxt_dto(JTextField txt_dto) {
        this.txt_dto = txt_dto;
    }

    public JTextField getTxt_fecha() {
        return txt_fecha;
    }

    public void setTxt_fecha(JTextField txt_fecha) {
        this.txt_fecha = txt_fecha;
    }

    public JTextField getTxt_lote() {
        return txt_lote;
    }

    public void setTxt_lote(JTextField txt_lote) {
        this.txt_lote = txt_lote;
    }

    public JTextField getTxt_nit() {
        return txt_nit;
    }

    public void setTxt_nit(JTextField txt_nit) {
        this.txt_nit = txt_nit;
    }

    public JTextField getTxt_nombre_prod() {
        return txt_nombre_prod;
    }

    public void setTxt_nombre_prod(JTextField txt_nombre_prod) {
        this.txt_nombre_prod = txt_nombre_prod;
    }

    public JTextField getTxt_precio_c() {
        return txt_precio_c;
    }

    public void setTxt_precio_c(JTextField txt_precio_c) {
        this.txt_precio_c = txt_precio_c;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_cant;
    private javax.swing.JLabel lbl_dto1;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_lote;
    private javax.swing.JLabel lbl_precio_c;
    private javax.swing.JLabel lbl_prod;
    private javax.swing.JLabel lbl_prov;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_dto;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_lote;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombre_prod;
    private javax.swing.JTextField txt_precio_c;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
