/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladores.Coordinador;
import static Vista.InicioVista.escritorio;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Genes
 */
public class ModificarDevolucionVista extends javax.swing.JInternalFrame {

    public static Coordinador coordinador;

    public ModificarDevolucionVista() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    public JButton getCmd_devolucion() {
        return cmd_modificar;
    }

    public void setCmd_devolucion(JButton cmd_devolucion) {
        this.cmd_modificar = cmd_devolucion;
    }

    public JTextArea getTxtArea_descrip() {
        return txtArea_descrip;
    }

    public void setTxtArea_descrip(JTextArea txtArea_descrip) {
        this.txtArea_descrip = txtArea_descrip;
    }

    public JTextField getTxt_id_factura() {
        return txt_id_factura;
    }

    public void setTxt_id_factura(JTextField txt_id_factura) {
        this.txt_id_factura = txt_id_factura;
    }

    public JTextField getTxt_id_prod() {
        return txt_id_prod;
    }

    public void setTxt_id_prod(JTextField txt_id_prod) {
        this.txt_id_prod = txt_id_prod;
    }
    public void limpiar(){
        this.getTxt_id_factura().setText("");
        this.getTxt_id_prod().setText("");
        this.getTxtArea_descrip().setText("");
    }
    public ModificarDevolucionVista(Coordinador coordinador) {
        this.coordinador = coordinador;
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        Dimension desktopSize = escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_descrip = new javax.swing.JLabel();
        txt_id_prod = new javax.swing.JTextField();
        lbl_id_prod = new javax.swing.JLabel();
        lbl_id_fac = new javax.swing.JLabel();
        txt_id_factura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_descrip = new javax.swing.JTextArea();
        cmd_modificar = new javax.swing.JButton();
        lbl_cant = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Modificar Devolucion");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icon_buscar.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_descrip.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        lbl_descrip.setText("Descripción:");
        jPanel1.add(lbl_descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 31, -1, 30));

        txt_id_prod.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txt_id_prod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_prodActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 123, -1));

        lbl_id_prod.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        lbl_id_prod.setText("Cod. Prod:");
        jPanel1.add(lbl_id_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 92, 80, -1));

        lbl_id_fac.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        lbl_id_fac.setText("Cod. Factura:");
        jPanel1.add(lbl_id_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        txt_id_factura.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txt_id_factura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_id_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 124, -1));

        txtArea_descrip.setColumns(20);
        txtArea_descrip.setRows(5);
        jScrollPane1.setViewportView(txtArea_descrip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 36, 233, 145));

        cmd_modificar.setBackground(new java.awt.Color(0, 51, 204));
        cmd_modificar.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        cmd_modificar.setForeground(new java.awt.Color(255, 255, 255));
        cmd_modificar.setText("Modificar Devolución");
        cmd_modificar.setBorder(null);
        cmd_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmd_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmd_modificarMouseExited(evt);
            }
        });
        cmd_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 140, 34));

        lbl_cant.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        lbl_cant.setText("Cantidad");
        jPanel1.add(lbl_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        txt_cant.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txt_cant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 123, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 590, 240));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_abajo.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 630, 50));

        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modificar Devolución");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 230, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImagenFondo/fondo_largo_dos.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jLabel7.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel7.setText("Datos de devolución:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_prodActionPerformed

    private void cmd_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_modificarMouseEntered
        // TODO add your handling code here:
        cmd_modificar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_cmd_modificarMouseEntered

    private void cmd_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_modificarMouseExited
        // TODO add your handling code here:
        cmd_modificar.setBackground(new Color(0, 51, 204));
    }//GEN-LAST:event_cmd_modificarMouseExited

    private void cmd_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_modificarActionPerformed
//        coordinador.modficarDevolucion();
    }//GEN-LAST:event_cmd_modificarActionPerformed

    private void txt_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_modificar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cant;
    private javax.swing.JLabel lbl_descrip;
    private javax.swing.JLabel lbl_id_fac;
    private javax.swing.JLabel lbl_id_prod;
    private javax.swing.JTextArea txtArea_descrip;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_id_factura;
    private javax.swing.JTextField txt_id_prod;
    // End of variables declaration//GEN-END:variables
}
